package pl.jcrusader.rebusydladzieci.game;

/**
 * Created by bogumil on 3/28/17.
 */

public class AnswersContainer {
    public static String[] ANSWERS
            =
            {
                    "",
                    "mikser",
                    "mak",
                    "kotlet",
                    "odwaga",
                    "traktor",
                    "lampart",
                    "kapusta",
                    "tama",
                    "makowiec",
                    "motyka",
                    "maskotka",
                    "laska",
                    "Karolina",
                    "ser",
                    "kosa",
                    "kotlet",
                    "rura",
                    "maska",
                    "wulkan",
                    "pajac",
                    "kłopot",
                    "landrynka",
                    "bajka",
                    "burak",
                    "okolica",
                    "nóżka",
                    "butelka",
                    "serce",
                    "list",
                    "odwaga",
                    "kotwica",
                    "słońce",
                    "tort",
                    "okulary",
                    "kompas",
                    "Eskimos",
                    "aktor",
                    "serdak",
                    "serce",
                    "serweta",
                    "mikser",
                    "tulipan",
                    "mgła",
                    "listy",
                    "ulewa",
                    "torba",
                    "rower",
                    "komputer",
                    "laska",
                    "rumak",
                    "makaron",
                    "rama",
                    "lama",
                    "oko",
                    "motor",
                    "pralka",
                    "dorota",
                    "lew",
                    "słoń",
                    "krokodyl",
                    "pantera",
                    "koliber",
                    "goryl",
                    "prima aprilis",
                    "cebula",
                    "konwalia",
                    "burak",
                    "bratek",
                    "tulipan",
                    "krokus",
                    "owoce zebrane",
                    "odlatują ptaki",
                    "deszczowa pogoda",
                    "daje się we znaki",
                    "łyżwiarstwo",
                    "hokej na lodzie",
                    "slalom narciarski",
                    "rekwizyt",
                    "kostium",
                    "kukiełka",
                    "maska",
                    "aktor",
                    "dekoracja",
                    "widz",
                    "scena",
                    "kalkulator",
                    "żelazko",
                    "magnetowid",
                    "zamrażarka",
                    "odkurzacz",
                    "staw",
                    "kałuża",
                    "strumyk",
                    "studnia",
                    "fontanna",
                    "jezioro"
            };
}
